spring:
  application:
    name: news-summary-app

  config:
    import: env.yml # 환경 변수 파일 불러오기 추가

  datasource:
    url: jdbc:postgresql://localhost:5432/email_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: daily

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: km802694@gmail.com
    password: jjpx jnxj ojwr bjww
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.example.demo.domain

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

news:
  api:
    url: ${NEWS_API_URL}

openai:
  api:
    url: ${OPENAI_API_URL}
    key: ${OPENAI_API_KEY}
